stages:
    - dotnet-build
    - dotnet-test
    - docker-build-push

dotnet-build:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    before_script:
        - "dotnet restore ./Petible-api"
    script:
        - "dotnet build ./Petible-api/Petible-api.sln"
    stage: dotnet-build
    
dotnet-test:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    stage: dotnet-test
    before_script:
        - "dotnet restore ./Petible-api"
    script:
        - "dotnet test ./Petible-api-testing"
    

docker-build-push:
    image: docker:latest
    services:
        - docker:dind
    only:
        - master
    before_script:
        - "docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}"
    script:
        - "docker build --tag ${ORG_NAME}/${DOCKER_CONTAINER_NAME} Petible-api"
        - "docker push ${ORG_NAME}/${DOCKER_CONTAINER_NAME}"
    stage: docker-build-push
